theme: jekyll-theme-cayman
title: We are Data Mine'R's!
description: The center of data analysis right beside you.

## Group Members
- Can Aytöre
- Ebru GEÇİCİ
- Mustafa KESER
- Nazlı GÜL
- Taha BAYAZ
- Talha ÜNLÜ